### ISSUE TITLE
SSL options are filtered

### ISSUE THREAD

**Issue by dlesl** [gen-smtp/gen_smtp#271]
Hi! I have been trying to pass options like `[{verify, verify_peer}, {cacertfile, Path}]` in `tls_options` but it seems they are being removed by [the filtering done here](https://github.com/gen-smtp/gen_smtp/blob/18ad70dc4a4e47adc57543221640145c4f928ec4/src/smtp_socket.erl#L53). Would you be open to relaxing this filtering?

**Comment by seriyps** [comment]
I think this filtering should be removed altogether, as well as `TCP_CONNECT_OPTIONS` filtering. Maybe forbidding some options which are critical for gen_smtp_client to function properly. But otherwise it should be the user's responsibility to provide correct options.
For example, we already don't do any socket option filtering for `gen_smtp_server`: https://github.com/gen-smtp/gen_smtp/blob/18ad70dc4a4e47adc57543221640145c4f928ec4/src/gen_smtp_server.erl#L90-L98
